### ISSUE TITLE
Imagen de preview no mostrada

### ISSUE THREAD

**Issue by andandandand** [the-chain/medicalchain-ipfs#1]
![image](https://user-images.githubusercontent.com/1021023/50498434-2141d980-0a17-11e9-9818-e6b4f4d099dd.png)

Imagen: 
![image](https://user-images.githubusercontent.com/1021023/50498460-5fd79400-0a17-11e9-92e8-40208edca9ea.png)

**Comment by Alex99y** [comment]
Al ser javascript, ambas funciones se ejecutan concurrentemente (Al ser asíncronas), la de guardar la imagen en un archivo y la de enviar la respuesta al cliente. Se arregló el problema dando un tiempo extra al servidor para que guarde la imagen antes de enviar la respuesta al cliente.

**Comment by Alex99y** [comment]
Reabro, para imágenes grandes/pesadas se necesita mas tiempo de carga.

**Comment by Alex99y** [comment]
Cierro, carga bien imágenes grandes.
